apiVersion: v2
name: protocol
version: 0.1.0
dependencies:
- name: rarible-helm-chart
  alias: ethereum-erc20-listener
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: polygon-erc20-listener
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: ethereum-erc20-api
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: polygon-erc20-api
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: ethereum-gateway
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: polygon-gateway
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: ethereum-order-api
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: polygon-order-api
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: ethereum-order-listener
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: polygon-order-listener
  repository: file://../resources/helm/rarible
  version: 0.1.0
#- name: rarible-helm-chart
#  alias: ethereum-order-migration
#  repository: file://../resources/helm/rarible
#  version: 0.1.0
- name: rarible-helm-chart
  alias: polygon-order-migration
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: ethereum-unlockable-api
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: polygon-unlockable-api
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: ethereum-nft-api
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: polygon-nft-api
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: ethereum-nft-listener
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: polygon-nft-listener
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: ethereum-nft-migration
  repository: file://../resources/helm/rarible
  version: 0.1.0
- name: rarible-helm-chart
  alias: polygon-nft-migration
  repository: file://../resources/helm/rarible
  version: 0.1.0
