global:
  network: rinkeby

ethereum-nft-listener:
  livenessProbe:
    initialDelaySeconds: 360s
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 256

polygon-nft-listener:
  livenessProbe:
    initialDelaySeconds: 360s
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 128
