global:
  network: rinkeby
  springExtraProfile: ''

sharedEnvironments: &sharedEnvironments
  EXTRA_ENV: placeHere
  # this secrets assigns automatically
  # RARIBLE_CORE_AGENT_SERVER:
  # MONGODB_HOSTS: 
  # MONGODB_USERNAME:
  # MONGODB_PASSWORD:
  # KAFKA_HOSTS: 

polygon-erc20-api:
  environments:
    <<: *sharedEnvironments

polygon-erc20-listener:
  environments:
    <<: *sharedEnvironments

polygon-gateway:
  environments:
    <<: *sharedEnvironments

polygon-order-api:
  environments:
    <<: *sharedEnvironments


polygon-order-listener:
  environments:
    <<: *sharedEnvironments


polygon-order-migration:
  environments:
    <<: *sharedEnvironments


polygon-unlockable-api:
  environments:
    <<: *sharedEnvironments

polygon-nft-api:
  environments:
    <<: *sharedEnvironments

polygon-nft-listener:
  environments:
    <<: *sharedEnvironments

polygon-nft-migration:
  environments:
    <<: *sharedEnvironments