spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}

rarible:
  ethereum:
    httpUrl: ${node.hosts}
    websocketUrl: ${node.webSocketHosts}

common:
  kafka-replica-set: ${kafka.hosts}
