common:
  chain-id: 80001
  exchange-contract-addresses:
    v1: "0x0000000000000000000000000000000000000000"
    v2: "0x2Fc743F5419637B93dDAC159715B902186300041"
    openSeaV1: "0x0000000000000000000000000000000000000000"
    openSeaV2: "0x0000000000000000000000000000000000000000"
    seaportV1: "0x0000000000000000000000000000000000000000"
    cryptoPunks: "0x0000000000000000000000000000000000000000"
    zeroEx: "0x533dc89624dcc012c7323b41f286bd2df478800b"
    looksrareV1: "0x0000000000000000000000000000000000000000"
    x2y2V1: "0x0000000000000000000000000000000000000000"
  auction-contract-addresses:
    v1: "0x0000000000000000000000000000000000000000"
  transfer-proxy-addresses:
    transfer-proxy: "0x02e21199D043dab90248f79d6A8d0c36832734B0"
    erc20-transfer-proxy: "0xa5a51d7b4933185da9c932e5375187f661cb0c69"
    erc721-lazy-transfer-proxy: "0x6c49c170c82C40709a32Fb4E827ad3011CD86227"
    erc1155-lazy-transfer-proxy: "0x9F7fBc52A53f85e57a5DAde35dFa14797A4dA412"
    crypto-punks-transfer-proxy: "0x0000000000000000000000000000000000000000"
  currency-contract-addresses:
    weth: "0xa6fa4fb5f76172d178d61b04b0ecd319c5d1c0aa"