common:
  chain-id: 5
  exchange-contract-addresses:
    v1: "0x0000000000000000000000000000000000000000"
    v2: "0x02afbD43cAD367fcB71305a2dfB9A3928218f0c1"
    openSeaV1: "0x0000000000000000000000000000000000000000"
    openSeaV2: "0x0000000000000000000000000000000000000000"
    seaportV1: "0x00000000006c3852cbef3e08e8df289169ede581"
    seaportV1_4: "0x00000000000001ad428e4906ae43d8f9852d0dd6"
    seaportV1_5: "0x00000000000000adc04c56bf30ac9d3c0aaf14dc"
    cryptoPunks: "0x0000000000000000000000000000000000000000"
    zeroEx: "0x0000000000000000000000000000000000000000"
    looksrareV1: "0xD112466471b5438C1ca2D218694200e49d81D047"
    looksrareV2: "0x35c2215f2ffe8917b06454eeeaba189877f200cf"
    x2y2V1: "0x0000000000000000000000000000000000000000"
  sudo-swap-addresses:
    pair-factory-v1: "0xf0202e9267930ae942f0667dc6d805057328f6dc"
    exponential-curve-v1: "0x0d807bd5ff2c4ef298755be30e22926b33244b0c"
    linear-curve-v1: "0xac6dcff6e13132f075e36ca3a7f403236f869438"
  auction-contract-addresses:
    v1: "0x0000000000000000000000000000000000000000"
  transfer-proxy-addresses:
    transfer-proxy: "0x21b0b84ffab5a8c48291f5ec9d9fdb9aef574052"
    erc20-transfer-proxy: "0x17cef9a8bf107d58e87c170be1652c06390bd990"
    erc721-lazy-transfer-proxy: "0x96102d9472c0338005cbf12fb7ea829f242c2809"
    erc1155-lazy-transfer-proxy: "0x1e1b6e13f0eb4c570628589e3c088bc92ad4db45"
    crypto-punks-transfer-proxy: "0x0000000000000000000000000000000000000000"
    seaport-transfer-proxy: "0x1e0049783f008a0085193e00003d00cd54003c71"
    looksrare-transfer-manager-erc721: "0xf8c81f3ae82b6efc9154c69e3db57fd4da57ab6e"
    looksrare-transfer-manager-erc1155: "0xf2ae42e871937f4e9ffb394c5a814357c16e06d6"
    looksrare-transfer-manager-non-compliant-erc721: "0x1c90a2f30090a79e0dee770161c1879b31b6f74d"
    looksrare-v2-transfer-manager: "0xc20e0cead98abbbeb626b77efb8dc1e5d781f90c"
  currency-contract-addresses:
    weth: "0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6"
  feature-flags:
    showSudoSwapOrdersWithOtherPlatforms: true
    getPoolInfoFromChain: false
    scanner-version: V2
  publish:
    publishAmmOrders: true
listener:
  seaport-load:
    enabled: true
    save-enabled: true
  tenderlyProperties:
    mapping:
      ethereum: goerli
rarible:
  seaport:
    network: goerli
  reservoir:
    testnet: true
