common:
  chain-id: 3
  node-type: GETH
  sudo-swap-addresses:
    pair-factory-v1: "0x3df054da59b1c0d5d9cee5edc9b58798526023b5"
    exponential-curve-v1: "0x42d8004fd14114c989654b825f993ca127eedbce"
    linear-curve-v1: "0xdd661d1daddb8f37751a45975c1f4851faffc9bd"
  feature-flags:
    showSudoSwapOrdersWithOtherPlatforms: true
    skipEventsIfNoTraceFound: true
  publish:
    publishAmmOrders: true
rarible:
  ethereum:
    max-frame-size: 10485760
listener:
  load-open-sea-orders: false
