listener:
  open-sea-exchange-domain-hash-v2: "0xd38471a54d114ee69fbb07d1769a0bbecd4f429ddf5932c7098093908e24bd9d"

  open-sea-orders-load-worker:
    enabled: true
  open-sea-orders-load-delay-worker:
    enabled: true
