common:
  chain-id: 80001
  exchange-contract-addresses:
    v1: "0x0000000000000000000000000000000000000000"
    v2: "0x2Fc743F5419637B93dDAC159715B902186300041"
    openSeaV1: "0x0000000000000000000000000000000000000000"
    openSeaV2: "0x0000000000000000000000000000000000000000"
    seaportV1: "0x00000000006c3852cbef3e08e8df289169ede581"
    seaportV1_4: "0x00000000000001ad428e4906ae43d8f9852d0dd6"
    seaportV1_5: "0x00000000000000adc04c56bf30ac9d3c0aaf14dc"
    cryptoPunks: "0x0000000000000000000000000000000000000000"
    zeroEx: "0x533dc89624dcc012c7323b41f286bd2df478800b"
    looksrareV1: "0x0000000000000000000000000000000000000000"
    x2y2V1: "0x0000000000000000000000000000000000000000"
  auction-contract-addresses:
    v1: "0x0000000000000000000000000000000000000000"
  transfer-proxy-addresses:
    transfer-proxy: "0xf8e4ecac18b65fd04569ff1f0d561f74effaa206"
    erc20-transfer-proxy: "0xa5a51d7b4933185da9c932e5375187f661cb0c69"
    erc721-lazy-transfer-proxy: "0x6c49c170c82C40709a32Fb4E827ad3011CD86227"
    erc1155-lazy-transfer-proxy: "0x9F7fBc52A53f85e57a5DAde35dFa14797A4dA412"
    seaport-transfer-proxy: "0x1e0049783f008a0085193e00003d00cd54003c71"
    crypto-punks-transfer-proxy: "0x0000000000000000000000000000000000000000"
  currency-contract-addresses:
    weth: "0xa6fa4fb5f76172d178d61b04b0ecd319c5d1c0aa"
  feature-flags:
    getPoolInfoFromChain: false
    scanner-version: V2
listener:
  seaport-load:
    enabled: true
    save-enabled: true
rarible:
  seaport:
    network: mumbai
