common:
  chain-id: 4
  node-type: GETH
  open-sea-nonce-increment: 1

rarible:
  opensea:
    testnet: true
  seaport:
    testnet: true

listener:
  openSeaEndpoint: ${rarible.opensea.endpoint}
  seaport-load:
    enabled: false
