common:
  chain-id: 200501
  exchange-contract-addresses:
    v1: "0x0000000000000000000000000000000000000000"
    v2: "0x6aABb267a1c440CfB5C200Ebcd078Efa9249492A"
    openSeaV1: "0x0000000000000000000000000000000000000000"
    openSeaV2: "0x0000000000000000000000000000000000000000"
    seaportV1: "0x0000000000000000000000000000000000000000"
    cryptoPunks: "0x0000000000000000000000000000000000000000"
    zeroEx: "0x0000000000000000000000000000000000000000"
    looksrareV1: "0x0000000000000000000000000000000000000000"
    x2y2V1: "0x0000000000000000000000000000000000000000"
  auction-contract-addresses:
    v1: "0x0000000000000000000000000000000000000000"
  transfer-proxy-addresses:
    transfer-proxy: "0xc6f33b62A94939E52E1b074c4aC1A801B869fDB2"
    erc20-transfer-proxy: "0x3586d3E6CDaE98d5F0eEaB737977Bc78406Da2BD"
    erc721-lazy-transfer-proxy: "0xeC47DA9591FC24F5a5F401e8D275526Cc5eE5d37"
    erc1155-lazy-transfer-proxy: "0x8812cFb55853da0968a02AaaEA84CD93EC4b42A1"
    crypto-punks-transfer-proxy: "0x0000000000000000000000000000000000000000"
  currency-contract-addresses:
    weth: "0x85de069e16a42880c57b0D6451D6C770EC1D3Bf7"
