global:
  network: 'testnet'

sharedEnvironments: &sharedEnvironments
  SPRING_CLOUD_CONSUL_ENABLED: false
#  SPRING_CLOUD_BOOTSTRAP_ENABLED: false
  SPRING_PROFILES_ACTIVE: '{{ .Values.global.blockchain }},{{ include "service.appEnv" $ }},{{ .Values.global.blockchain }}-{{ include "service.appEnv" $ }}'
  RARIBLE_CORE_APM_AGENT_ENABLED: false
  LOGGING_LOGSTASH_TCPSOCKET_ENABLED: true
#  LOGGING_LOGSTASH_TCPSOCKET_DESTINATIONS: ""
  RARIBLE_ETHEREUM_MAXFRAMESIZE: 10485760
  COMMON_CRYPTOPUNKSCONTRACTADDRESS: '0x73AEc342B748095Ad26b6B90038944a742a6151E'
  COMMON_OPENSEALAZYMINTADDRESS: '0x88b48f654c30e99bc2e4a1559b4dcf1ad93fa656'
  COMMON_ROYALTYREGISTRYADDRESS: '0xA094E566b61b3c2D88ACf7Cc15e3Dd0FA83F32af'
  COMMON_FACTORY_ERC721RARIBLE: "0x31575E4426d195f6082aDdcD44e97cB4CEa1291C"
  COMMON_FACTORY_ERC721RARIBLEUSER: "0xe5bF86F2FC1e0C704A8b2C095aD92C59100C63Ac"
  COMMON_FACTORY_ERC1155RARIBLE: "0x3Df4035EC62B97b5e3B5f160Cb84dCe4A9CB545D"
  COMMON_FACTORY_ERC1155RARIBLEUSER: "0x5a5773ac6b87f15dF215A78BEfdce478C33D8418"
  API_CHAINID: 5
  COMMON_CHAINID: 5
  APPLICATION_ENVIRONMENT: "infura-test"
  # this secrets assigns automatically
  # RARIBLE_CORE_AGENT_SERVER:
  # SPRING_DATA_MONGODB_HOST:
  # SPRING_DATA_MONGODB_PORT:
  # SPRING_DATA_MONGODB_USERNAME:
  # SPRING_DATA_MONGODB_PASSWORD:
  # COMMON_KAFKAREPLICASET:
  # COMMON_BASEPUBLICAPIURL: 
  # BLOCKCHAIN_SCANNER_KAFKA_BROKERREPLICASET:
  # RARIBLE_LOADER_BROKERREPLICASET: 
  # RARIBLE_ETHEREUM_HTTPURL: 
  # RARIBLE_ETHEREUM_WEBSOCKETURL:

sharedTolerations: &sharedTolerations
  effect: NoSchedule
  key: env
  operator: Equal
  value: infura-test

ethereum-erc20-api:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-erc20

ethereum-erc20-listener:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-erc20
    SPRING_TASK_SCHEDULING_POOL_SIZE: 30
    ETHEREUMBLOCKPROCESSINGDELAY: 5000
    ETHEREUMMAXPROCESSTIME: 1200000
    USENEWMONGOINDEX: true

ethereum-gateway:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    RARIBLE_CORE_NGINXEXPOSE_ENABLED: false

orderEnvironment: &orderEnvironment
    COMMON_AUCTIONCONTRACTADDRESSES_V1: "0xA8B4ab8aE8C40cD6b11a3A6BFCb00B2B8106150f"
    COMMON_EXCHANGECONTRACTADDRESSES_CRYPTOPUNKS: "0x73AEc342B748095Ad26b6B90038944a742a6151E"
    COMMON_EXCHANGECONTRACTADDRESSES_HOLDERV1: "0x0000000000000000000000000000000000000000"
    COMMON_EXCHANGECONTRACTADDRESSES_OPENSEAV1: "0x5206e78b21ce315ce284fb24cf05e0585a93b1d9"
    COMMON_EXCHANGECONTRACTADDRESSES_OPENSEAV2: "0xdd54d660178b28f6033a953b0e55073cfa7e3744"
    COMMON_EXCHANGECONTRACTADDRESSES_V1: "0xda381535565b97640a6453fa7a1a7b161af78cbe"
    COMMON_EXCHANGECONTRACTADDRESSES_V2: "0x18a2553ef1aaE12d9cd158821319e26A62feE90E"
    COMMON_EXCHANGECONTRACTADDRESSES_ZEROEX: "0x0000000000000000000000000000000000000000"
    COMMON_FEATUREFLAGS_SHOWALLORDERSBYDEFAULT: true
    COMMON_FEATUREFLAGS_SHOWOPENSEAORDERSWITHOTHERPLATFORMS: true
    COMMON_FEATUREFLAGS_USECOMMONTRANSACTIONTRACEPROVIDER: false
    COMMON_PUBLISH_PUBLISHOPENSEAORDERSTOCOMMONTOPIC: true
    COMMON_TRANSFERPROXYADDRESSES_CRYPTOPUNKSTRANSFERPROXY: "0x83276B1612e668b7Ef62eFce54b1128315E0C421"
    COMMON_TRANSFERPROXYADDRESSES_ERC1155LAZYTRANSFERPROXY: "0xD504e84B42947Ee6f07dBE28763896EA3A2bc5e9"
    COMMON_TRANSFERPROXYADDRESSES_ERC20TRANSFERPROXY: "0xC5BBd75789bD007784A0046094d19aCeA1A79eB1"
    COMMON_TRANSFERPROXYADDRESSES_ERC721LAZYTRANSFERPROXY: "0x0fE65B68Eb627c21EAF3cfe8183C4F946F3d48BD"
    COMMON_TRANSFERPROXYADDRESSES_TRANSFERPROXY: "0xa2eEBb837aEF89369Ad117568d75348e6174520e"
    COMMON_PROTOCOLCOMMISSION: 0
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-order

ethereum-order-api:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    <<: *orderEnvironment

ethereum-order-listener:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    <<: *orderEnvironment
    BLOCKCHAIN_SCANNER_ETHEREUM_SCAN_BATCHLOAD_BATCHSIZE: 100
    ETHEREUMBLOCKPROCESSINGDELAY: 5000
    LISTENER_LOADOLDOPENSEAORDERS: true
    LISTENER_LOADOPENSEADELAY: "180s"
    LISTENER_LOADOPENSEAORDERVERSION: true
    LISTENER_LOADOPENSEAORDERS: true
    LISTENER_OPENSEANONCEINCREMENT: 1
    LISTENER_OPENSEAORDERSIDE: "SELL"
    LISTENER_PRICEUPDATEENABLED: true
    LISTENER_PUBLISHTASKDELAYMS: 100
    LISTENER_RESETMAKESTOCKENABLED: true
    LISTENER_UPDATESTATUSBYSTARTENDENABLED: true
    LISTENER_UPDATESTATUSBYSTARTENDRATE: "PT1M"
    RARIBLE_ETHEREUM_MAXFRAMESIZE: 209715200
    SPRING_TASK_SCHEDULING_POOL_SIZE: 60
    USENEWMONGOINDEX: true
ethereum-order-migration:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    <<: *orderEnvironment

ethereum-unlockable-api:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-unlockable
ethereum-nft-api: 
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    RARIBLE_LOADER_LOADTASKSBATCHSIZE: 50
    RARIBLE_LOADER_WORKERS: 32
    ETHEREUMBLOCKPROCESSINGDELAY: 5000
    ETHEREUMMAXPROCESSTIME: 1200000
    USENEWMONGOINDEX: true
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-nft

ethereum-nft-listener:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    COMMON_FEATUREFLAGS_SCANNERVERSION: V2
    COMMON_FEATUREFLAGS_REDUCEVERSION: V2
    BLOCKCHAIN_SCANNER_ETHEREUM_SCAN_BATCHLOAD_BATCHSIZE: 25
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-nft

ethereum-nft-migration:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    SPRING_DATA_MONGODB_DATABASE: test-protocol-ethereum-nft
